name: Deploy my lambda function

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v2
      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
             cd function
             python -m pip install --upgrade pip
             if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r ../{{ github.sha }}.zip .
      - name: Archive artifact
        uses: action/upload-artifact@v2
        with:
          name: zipped bundle
          path: {{ github.sha }}.zip
          
