# This is a placeholder so actions won't default to a getting started page

name: Placeholder

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  init:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Run
      run: dotnet run
