name: Deploy feature branches to nonproduction

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-14911d813caebc1df55cc6366-nonprodbucket-1ihdbl8ifaml4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Deploy bundle to bucket
        run: |
            echo 'copying files to s3 bucket'
            aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
