name: Deploy site to production s3 bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-235ade7a172d8d0f151a37b974fa-prodbucket-1i28yp4vm7htd
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy files to s3 bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive --acl public-read
